import type { CodexPresetDefinition } from './preset-base'

export const LIGHT_CODEX_THEME_DEFINITIONS: CodexPresetDefinition[] = [
  {
    id: 'absolutely-light',
    name: 'Absolutely',
    variant: 'light',
    codeThemeId: 'absolutely',
    theme: {
      accent: '#cc7d5e',
      contrast: 45,
      fonts: { code: null, ui: null },
      ink: '#2d2d2b',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#00c853', diffRemoved: '#ff5f38', skill: '#cc7d5e' },
      surface: '#f9f9f7',
    },
  },
  {
    id: 'catppuccin-light',
    name: 'Catppuccin',
    variant: 'light',
    codeThemeId: 'catppuccin',
    theme: {
      accent: '#8839ef',
      contrast: 45,
      fonts: { code: null, ui: null },
      ink: '#4c4f69',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#40a02b', diffRemoved: '#d20f39', skill: '#8839ef' },
      surface: '#eff1f5',
    },
  },
  {
    id: 'codex-light',
    name: 'Codex',
    variant: 'light',
    codeThemeId: 'codex',
    theme: {
      accent: '#0169cc',
      contrast: 45,
      fonts: { code: null, ui: null },
      ink: '#0d0d0d',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#00a240', diffRemoved: '#e02e2a', skill: '#751ed9' },
      surface: '#ffffff',
    },
  },
  {
    id: 'everforest-light',
    name: 'Everforest',
    variant: 'light',
    codeThemeId: 'everforest',
    theme: {
      accent: '#93b259',
      contrast: 40,
      fonts: { code: '"SFMono-Regular"', ui: 'Geist, Inter' },
      ink: '#5c6a72',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#8da101', diffRemoved: '#f85552', skill: '#df69ba' },
      surface: '#fdf6e3',
    },
  },
  {
    id: 'github-light',
    name: 'GitHub',
    variant: 'light',
    codeThemeId: 'github',
    theme: {
      accent: '#0969da',
      contrast: 40,
      fonts: { code: '"SFMono-Regular"', ui: 'Geist, Inter' },
      ink: '#1f2328',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#1a7f37', diffRemoved: '#cf222e', skill: '#8250df' },
      surface: '#ffffff',
    },
  },
  {
    id: 'linear-light',
    name: 'Linear',
    variant: 'light',
    codeThemeId: 'linear',
    theme: {
      accent: '#5e6ad2',
      contrast: 40,
      fonts: { code: '"SFMono-Regular"', ui: 'Inter' },
      ink: '#1b1b1b',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#52a450', diffRemoved: '#c94446', skill: '#8160d8' },
      surface: '#fcfcfd',
    },
  },
  {
    id: 'notion-light',
    name: 'Notion',
    variant: 'light',
    codeThemeId: 'notion',
    theme: {
      accent: '#3183d8',
      contrast: 40,
      fonts: { code: null, ui: null },
      ink: '#37352f',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#008000', diffRemoved: '#a31515', skill: '#0000ff' },
      surface: '#ffffff',
    },
  },
  {
    id: 'one-light',
    name: 'One',
    variant: 'light',
    codeThemeId: 'one',
    theme: {
      accent: '#526fff',
      contrast: 40,
      fonts: { code: null, ui: null },
      ink: '#383a42',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#3bba54', diffRemoved: '#e45649', skill: '#526fff' },
      surface: '#fafafa',
    },
  },
  {
    id: 'proof-light',
    name: 'Proof',
    variant: 'light',
    codeThemeId: 'proof',
    theme: {
      accent: '#3d755d',
      contrast: 40,
      fonts: { code: null, ui: null },
      ink: '#2f312d',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#3d755d', diffRemoved: '#ba2623', skill: '#5f6ac2' },
      surface: '#f5f3ed',
    },
  },
  {
    id: 'raycast-light',
    name: 'Raycast',
    variant: 'light',
    codeThemeId: 'raycast',
    theme: {
      accent: '#ff6363',
      contrast: 40,
      fonts: { code: '"Jetbrains Mono"', ui: 'Inter' },
      ink: '#030303',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#006b4f', diffRemoved: '#b12424', skill: '#9a1b6e' },
      surface: '#ffffff',
    },
  },
  {
    id: 'rose-pine-light',
    name: 'Rose Pine',
    variant: 'light',
    codeThemeId: 'rose-pine',
    theme: {
      accent: '#d7827e',
      contrast: 40,
      fonts: { code: '"Jetbrains Mono"', ui: 'Inter' },
      ink: '#575279',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#56949f', diffRemoved: '#797593', skill: '#907aa9' },
      surface: '#faf4ed',
    },
  },
]
