import type { CodexPresetDefinition } from './preset-base'

export const DARK_CODEX_THEME_DEFINITIONS: CodexPresetDefinition[] = [
  {
    id: 'absolutely',
    name: 'Absolutely',
    variant: 'dark',
    codeThemeId: 'absolutely',
    theme: {
      accent: '#cc7d5e',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#f9f9f7',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#00c853', diffRemoved: '#ff5f38', skill: '#cc7d5e' },
      surface: '#2d2d2b',
    },
  },
  {
    id: 'codex',
    name: 'Codex',
    variant: 'dark',
    codeThemeId: 'codex',
    theme: {
      accent: '#0169cc',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#fcfcfc',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#00a240', diffRemoved: '#e02e2a', skill: '#b06dff' },
      surface: '#111111',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    variant: 'dark',
    codeThemeId: 'dracula',
    theme: {
      accent: '#ff79c6',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#f8f8f2',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#50fa7b', diffRemoved: '#ff5555', skill: '#ff79c6' },
      surface: '#282a36',
    },
  },
  {
    id: 'everforest',
    name: 'Everforest',
    variant: 'dark',
    codeThemeId: 'everforest',
    theme: {
      accent: '#a7c080',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#d3c6aa',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#a7c080', diffRemoved: '#e67e80', skill: '#d699b6' },
      surface: '#2d353b',
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    variant: 'dark',
    codeThemeId: 'github',
    theme: {
      accent: '#1f6feb',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#e6edf3',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#3fb950', diffRemoved: '#f85149', skill: '#bc8cff' },
      surface: '#0d1117',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    variant: 'dark',
    codeThemeId: 'gruvbox',
    theme: {
      accent: '#458588',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#ebdbb2',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#ebdbb2', diffRemoved: '#cc241d', skill: '#b16286' },
      surface: '#282828',
    },
  },
  {
    id: 'linear',
    name: 'Linear',
    variant: 'dark',
    codeThemeId: 'linear',
    theme: {
      accent: '#606acc',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Inter' },
      ink: '#e3e4e6',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#69c967', diffRemoved: '#ff7e78', skill: '#c2a1ff' },
      surface: '#0f0f11',
    },
  },
  {
    id: 'lobster',
    name: 'Lobster',
    variant: 'dark',
    codeThemeId: 'lobster',
    theme: {
      accent: '#ff5c5c',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Satoshi' },
      ink: '#e4e4e7',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#22c55e', diffRemoved: '#ff5c5c', skill: '#3b82f6' },
      surface: '#111827',
    },
  },
  {
    id: 'material',
    name: 'Material',
    variant: 'dark',
    codeThemeId: 'material',
    theme: {
      accent: '#80cbc4',
      contrast: 27,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Satoshi' },
      ink: '#eeffff',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#c3e88d', diffRemoved: '#f07178', skill: '#c792ea' },
      surface: '#212121',
    },
  },
  {
    id: 'matrix',
    name: 'Matrix',
    variant: 'dark',
    codeThemeId: 'matrix',
    theme: {
      accent: '#1eff5a',
      contrast: 27,
      fonts: { code: null, ui: 'ui-monospace, "SFMono-Regular", "SF Mono", Menlo, Consolas, "Liberation Mono", monospace' },
      ink: '#b8ffca',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#1eff5a', diffRemoved: '#fa423e', skill: '#1eff5a' },
      surface: '#040805',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    variant: 'dark',
    codeThemeId: 'monokai',
    theme: {
      accent: '#99947c',
      contrast: 27,
      fonts: { code: null, ui: 'ui-monospace, "SFMono-Regular", "SF Mono", Menlo, Consolas, "Liberation Mono", monospace' },
      ink: '#f8f8f2',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#86b42b', diffRemoved: '#c4265e', skill: '#8c6bc8' },
      surface: '#272822',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    variant: 'dark',
    codeThemeId: 'night-owl',
    theme: {
      accent: '#44596b',
      contrast: 27,
      fonts: { code: null, ui: 'ui-monospace, "SFMono-Regular", "SF Mono", Menlo, Consolas, "Liberation Mono", monospace' },
      ink: '#d6deeb',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#c5e478', diffRemoved: '#ef5350', skill: '#c792ea' },
      surface: '#011627',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    variant: 'dark',
    codeThemeId: 'nord',
    theme: {
      accent: '#88c0d0',
      contrast: 27,
      fonts: { code: null, ui: 'ui-monospace, "SFMono-Regular", "SF Mono", Menlo, Consolas, "Liberation Mono", monospace' },
      ink: '#d8dee9',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#a3be8c', diffRemoved: '#bf616a', skill: '#b48ead' },
      surface: '#2e3440',
    },
  },
  {
    id: 'notion',
    name: 'Notion',
    variant: 'dark',
    codeThemeId: 'notion',
    theme: {
      accent: '#3183d8',
      contrast: 27,
      fonts: { code: null, ui: null },
      ink: '#d9d9d8',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#4ec9b0', diffRemoved: '#fa423e', skill: '#3183d8' },
      surface: '#191919',
    },
  },
  {
    id: 'one',
    name: 'One',
    variant: 'dark',
    codeThemeId: 'one',
    theme: {
      accent: '#4d78cc',
      contrast: 27,
      fonts: { code: null, ui: null },
      ink: '#abb2bf',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#8cc265', diffRemoved: '#e05561', skill: '#c162de' },
      surface: '#282c34',
    },
  },
  {
    id: 'oscurange',
    name: 'Oscurange',
    variant: 'dark',
    codeThemeId: 'oscurange',
    theme: {
      accent: '#f9b98c',
      contrast: 27,
      fonts: { code: '"Jetbrains Mono"', ui: 'Inter' },
      ink: '#e6e6e6',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#40c977', diffRemoved: '#fa423e', skill: '#479ffa' },
      surface: '#0b0b0f',
    },
  },
  {
    id: 'raycast',
    name: 'Raycast',
    variant: 'dark',
    codeThemeId: 'raycast',
    theme: {
      accent: '#ff6363',
      contrast: 27,
      fonts: { code: '"Jetbrains Mono"', ui: 'Inter' },
      ink: '#fefefe',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#59d499', diffRemoved: '#ff6363', skill: '#cf2f98' },
      surface: '#101010',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rose Pine',
    variant: 'dark',
    codeThemeId: 'rose-pine',
    theme: {
      accent: '#ea9a97',
      contrast: 27,
      fonts: { code: '"Jetbrains Mono"', ui: 'Inter' },
      ink: '#e0def4',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#9ccfd8', diffRemoved: '#908caa', skill: '#c4a7e7' },
      surface: '#232136',
    },
  },
  {
    id: 'sentry',
    name: 'Sentry',
    variant: 'dark',
    codeThemeId: 'sentry',
    theme: {
      accent: '#7055f6',
      contrast: 27,
      fonts: { code: null, ui: null },
      ink: '#e6dff9',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#8ee6d7', diffRemoved: '#fa423e', skill: '#7055f6' },
      surface: '#2d2935',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    variant: 'dark',
    codeThemeId: 'solarized',
    theme: {
      accent: '#d30102',
      contrast: 27,
      fonts: { code: null, ui: null },
      ink: '#839496',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#859900', diffRemoved: '#dc322f', skill: '#d33682' },
      surface: '#002b36',
    },
  },
  {
    id: 'temple',
    name: 'Temple',
    variant: 'dark',
    codeThemeId: 'temple',
    theme: {
      accent: '#e4f222',
      contrast: 27,
      fonts: { code: null, ui: null },
      ink: '#c7e6da',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#40c977', diffRemoved: '#fa423e', skill: '#e4f222' },
      surface: '#02120c',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    variant: 'dark',
    codeThemeId: 'tokyo-night',
    theme: {
      accent: '#3d59a1',
      contrast: 27,
      fonts: { code: null, ui: null },
      ink: '#a9b1d6',
      opaqueWindows: false,
      semanticColors: { diffAdded: '#449dab', diffRemoved: '#914c54', skill: '#9d7cd8' },
      surface: '#1a1b26',
    },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    variant: 'dark',
    codeThemeId: 'vercel',
    theme: {
      accent: '#006efe',
      contrast: 50,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Geist, Inter' },
      ink: '#ededed',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#00ad3a', diffRemoved: '#f13342', skill: '#9540d5' },
      surface: '#000000',
    },
  },
  {
    id: 'vscode-plus',
    name: 'VS Code+',
    variant: 'dark',
    codeThemeId: 'vscode-plus',
    theme: {
      accent: '#007acc',
      contrast: 50,
      fonts: { code: '"Geist Mono", ui-monospace, "SFMono-Regular"', ui: 'Geist, Inter' },
      ink: '#d4d4d4',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#369432', diffRemoved: '#f44747', skill: '#000080' },
      surface: '#1e1e1e',
    },
  },
  {
    id: 'xcode',
    name: 'Xcode',
    variant: 'dark',
    codeThemeId: 'xcode',
    theme: {
      accent: '#5482ff',
      contrast: 50,
      fonts: { code: '"SFMono-Medium"', ui: 'Geist, Inter' },
      ink: '#ffffff',
      opaqueWindows: true,
      semanticColors: { diffAdded: '#67b7a4', diffRemoved: '#fc6a5d', skill: '#5482ff' },
      surface: '#1f1f24',
    },
  },
]
